### ISSUE TITLE
Add DELETE_DATE column to EK_* temp tables

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/aiw-i2b2-etl#1]
The main file where work is needed is src/main/resources/i2b2-data-schema-changelog.xml. Work may be needed in the Java code if SQL queries fail due to the added column, or in the stored procedure code if any stored procedures fail due to the added column. The stored procedures for Oracle and PostgreSQL are in src/main/resources/sql.

**Comment by akalsan** [comment]
do we want to add dummy DELETE_DATE values for the test data?

**Comment by arpost** [comment]
We'll add dummy DELETE_DATE values to issue #3.
