### ISSUE TITLE
Add modifiers to ICD-10 diagnosis ontology

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/aiw-i2b2-etl#23]
It should have the same modifiers as the ICD-9 diagnosis ontology.

**Comment by arpost** [comment]
The main question here is at what level in the hierarchy should we start including modifiers. I think it's best to include them as close to the root of the diagnosis hierarchy as possible. Due to the structure of the ICD10 ontology that we obtained, I believe you'll need to add them starting at c_hlevel 1 (because the concepts at c_hlevel 1 are containers not draggable folders).

**Comment by akalsan** [comment]
going by the modifiers for icd9Diagnosis hierarchy, the modifiers look different in the latest aiw-i2b2-etl project compared to the ones in the ACT ontology. like for example the only modifier in the aiw-i2b2-etl ontology is diagnosis priority with no children stating principal/secondary. Attached a screenshot. the ACT modifiers are many more. attached a screenshot of that as well
![act_ontology_modifiers](https://cloud.githubusercontent.com/assets/14340728/14117555/2e8bee44-f5b3-11e5-8985-eb20e5b0e525.png)
![latest_aiw-i2b2_etl_modifiers](https://cloud.githubusercontent.com/assets/14340728/14117556/2e928966-f5b3-11e5-8335-07524f3c8f4c.png)

**Comment by akalsan** [comment]
Do we just need diagnosis priority modifier for now?

**Comment by arpost** [comment]
Per F2F discussion, we want diagnosis priority and diagnosis source modifiers.
