### ISSUE TITLE
vital status has to be in a folder

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/aiw-i2b2-etl#32]
It appears that the breakdowns in the Run Query dialog in i2b2 do not work unless there is a folder with one or more child values. We need to change Vital Status in the Eureka ontology to fit this constraint. It should be:

```
Demographics
    Vital Status
        Known Deceased
```

This bug in our ontology breaks multiple of the breakdown options in the Run Query dialog. The JBoss log complains about Vital Status in all cases.

**Comment by akalsan** [comment]
i just ran a query in i2b2webprod1.cc.emory.edu to show the vital status breakdown and i have attached the screenshot. On the VM that vagrant creates, we need to add the entries to QT_BREAKDOWN_PATH and it should work. I just added the correct entries to QT_BREAKDOWN_PATH table in the VM on my machine and all the breakdowns work fine. Attaching  a screenshot of the QT_BREAKDOWN_PATH values. If you agree with this, we could update ansible scripts to insert values into this table once the metadata is loaded. also, any particular environment that jboss logs show errors? i checked the i2b2webprod and the VM, didnt see anything in the jboss logs regarding vital status as long  QT_BREAKDOWN_PATH is correct. 
![screen shot 2016-07-06 at 2 38 05 pm](https://cloud.githubusercontent.com/assets/14340728/16630339/fb2aa162-4387-11e6-9bdb-7db0af998965.png)
![screen shot 2016-07-06 at 2 38 19 pm](https://cloud.githubusercontent.com/assets/14340728/16630340/fb2c7a5a-4387-11e6-9d3d-4126d177401f.png)
![screen shot 2016-07-06 at 2 42 31 pm](https://cloud.githubusercontent.com/assets/14340728/16630341/fb2ca228-4387-11e6-8234-9568db060a90.png)

**Comment by akalsan** [comment]
when the metadata is loaded as part of the job submission, i believe that the valuesets are coming from patientDetailsProposition.properties file in aiw-i2b2-etl/resources. Since the VitalStatus property does not have valueset defined in the file, the logic in aiw-i2b2-etl makes this a leaf node. I would think adding the valueset to patientDetailsProposition.properties should fix the problem.

**Comment by arpost** [comment]
This issue is on hold pending a decision from Andrew on how to implement. Ideally, the solution belongs in aiw-i2b2-etl.
