### ISSUE TITLE
Implement logic in the Postgresql stored procedures to delete records

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/aiw-i2b2-etl#7]
Depends on #1.

**Comment by arpost** [comment]
In reviewing the stored procedure updates, I noticed a pattern that there's an UPDATE statement with a WHERE clause to skip updating records marked for deletion followed by a DELETE statement that deletes records marked for deletion. If you reversed the order of those statements, you might be able to remove that part of the WHERE clause in the UPDATE statement.

**Comment by mStack5522** [comment]
Okay, thanks for the suggestion!
