### ISSUE TITLE
No vital sign c_metadataxml

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/aiw-i2b2-etl#9]
in src/main/resources/dbmigration/eureka-ontology-EK_VITALS-changelog.xml. Needed to make i2b2 pop up the value threshold dialog. See how it's done in eureka-ontology-EK_LABS-changelog.xml for an example.

**Comment by akalsan** [comment]
<img width="626" alt="screen shot 2016-03-03 at 8 21 00 am" src="https://cloud.githubusercontent.com/assets/14340728/13495489/09b9f9de-e119-11e5-85bd-545e3063ad99.png">

i made the change for this. The i2b2 documentation says this field is only used for labs and as i was testing it i see the wordings in the pop up "Searches by Lab values can be constrained by the high/low flag set by the performing laboratory, or by the values themselves." like in the attached screenshot. not sure if this makes sense for vital signs and we want to go ahead with the change. is there any resource that points to using this metadataxml field with vitals?

**Comment by arpost** [comment]
Yes, go ahead with the change. It's the only way to get i2b2 to allow setting a value threshold.
